apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sftp-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 22
  selector:
    app: sftp
