apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sftp
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - name: sftp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 22
        args:
        - "{{ .Values.users[0].username }}:{{ .Values.users[0].password }}:{{ .Values.users[0].uid }}"
        volumeMounts:
        - name: storage
          mountPath: /home/{{ .Values.users[0].username }}/upload
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
